#!/usr/bin/env ruby
# pre receive

input_lines = []
ARGF.each_line {|line|
  input_lines.push line
}
if input_lines.length > 1
  puts "[CHECK] Multiple refs pushed. This is almost definitely not what you want."
  puts "[CHECK] Please only push a single tag for deployment. Push rejected."
  exit 1
end

old, @new, ref = input_lines[0].split " "

if ref.include? "refs/tags"
  tagname = ref.split('/')[-1]
  puts "[CHECK] Tag pushed: #{tagname}"
  if (@new =~ /^0*$/)
    puts "[CHECK] Tag deleted. Will try to rollback release #{tagname}."
    exit 0
  end
  if tagname.start_with? "staging"
    puts "[CHECK] Will deploy to staging."
  elsif tagname.start_with? "release"
    puts "[CHECK] Will deploy to production."
  else
    puts "[CHECK] Tag #{tagname} is neither staging nor release. Push rejected."
    puts "[CHECK] Please only push tags starting with 'release' or 'staging'."
    exit 1
  end
elsif ref.include? "refs/heads"
  puts "[CHECK] HEAD pushed: #{ref.split('/')[-1]}"
  puts "[CHECK] Please only push release or staging tags. Push rejected."
  exit 1
else
  puts "[DEPLOY] Invalid ref pushed. Push rejected."
  exit 1
end
